# Sample Configuration File for Grin-Pool
#
# When running the grin-pool executable without specifying any command line
# arguments, it will look for this file in The working directory

#########################################
### POOL CONFIGURATION                ###
#########################################

#
# Configuration for the Stratum Pool
[grin_pool]
log_dir = "/usr/local/var/"

[workers]
listen_address = "0.0.0.0"
port_difficulty = [
 [3333, 1],
]

[server]
id = 1

# Configuration for access to upstream grin node
[grin_node]
address = "47.99.92.164"
api_port = 13413
stratum_port = 13416
login = "GrinPool"
password = ""

[producer]
#brokers = ["localhost:9092"]
#topic = "my-topic"
brokers = ["lan.kafka01hz.pool:29092", "lan.kafka02hz.pool:29092", "lan.kafka03hz.pool:29092"]
topic = "ShareLogGrin"
partitions = 1
options = {"required_acks" = "none", "ack_timeout" = "1000", "conn_idle_timeout" =  "500"}
